export default [
  {
    _id: "1",
    item_identifier: "home-page",
    created_at: "1976-04-19T12:59-0500",
    likes: [],
    replies_count: 2,
    author: {
      _id: "1",
      name: "Michael Gough",
      img: "https://flowbite.com/docs/images/people/profile-picture-2.jpg",
    },
    body: "Very straight-to-point article. Really worth time reading. Thank you! But tools are just the instruments for the UX designers. The knowledge of the design tools are as important as the creation of the design strategy.",
  },
  {
    _id: "2",
    item_identifier: "home-page",
    parent: "1",
    likes: ["2"],
    replies_count: 1,
    created_at: "1976-04-19T12:59-0500",
    author: {
      _id: "2",
      name: "Jese Leos",
      img: "https://flowbite.com/docs/images/people/profile-picture-5.jpg",
    },
    body: "Much appreciated! Glad you liked it ☺️",
  },
  {
    _id: "3",
    item_identifier: "home-page",
    parent: "2",
    likes: [],
    replies_count: 0,
    created_at: "1976-04-19T12:59-0500",
    author: {
      _id: "3",
      name: "Bonnie Green",
      img: "https://flowbite.com/docs/images/people/profile-picture-3.jpg",
    },
    body: "The article covers the essentials, challenges, myths and stages the UX designer should consider while creating the design strategy.",
  },
  {
    _id: "4",
    item_identifier: "home-page",
    likes: ["2"],
    replies_count: 0,
    created_at: "1976-04-19T12:59-0500",
    author: {
      _id: "4",
      name: "Harry Potter",
      img: "https://static.independent.co.uk/s3fs-public/thumbnails/image/2013/09/12/17/potter.jpg",
    },
    body: "Thanks for sharing this. I do came from the Backend development and explored some of the tools to design my Side Projects.",
  },
  {
    _id: "5",
    item_identifier: "home-page",
    parent: "1",
    likes: [],
    replies_count: 0,
    created_at: "1976-04-19T12:59-0500",
    author: {
      _id: "4",
      name: "Harry Potter",
      img: "https://flowbite.com/docs/images/people/profile-picture-4.jpg",
    },
    body: "Thanks for sharing this. I do came from the Backend development and explored some of the tools to design my Side Projects.",
  },
  {
    _id: "6",
    item_identifier: "QnA",
    parent: "123",
    likes: [],
    replies_count: 0,
    created_at: "1976-04-19T12:59-0500",
    author: {
      _id: "4",
      name: "Helene Engels",
      img: "https://flowbite.com/docs/images/people/profile-picture-4.jpg",
    },
    body: "XXXXXXXXXX shouldn't appear.",
  },
  {
    _id: "7",
    item_identifier: "QnA",
    parent: "23",
    likes: [],
    replies_count: 0,
    created_at: "1976-04-19T12:59-0500",
    author: {
      _id: "4",
      name: "Helene Engels",
      img: "https://flowbite.com/docs/images/people/profile-picture-4.jpg",
    },
    body: "XXXXXXXXXX shouldn't appear 222.",
  },
];
